export const CODES = {
  // Project / config
  VE_PROJECT_001_MISSING_CONFIG: 'VE_PROJECT_001',
  VE_PROJECT_002_ROUTE_NOT_FOUND: 'VE_PROJECT_002',
  VE_PROJECT_990_UNSUPPORTED_OS: 'VE_PROJECT_990',
  VE_PROJECT_991_NODE_TOO_OLD: 'VE_PROJECT_991',
  VE_PROJECT_992_NEXT_NOT_SUPPORTED: 'VE_PROJECT_992',
  VE_CONFIG_001_UNSAFE_ENV_ACCESS: 'VE_CONFIG_001',
  // Preview / adapter
  VE_PREVIEW_001_WORKER_TIMEOUT: 'VE_PREVIEW_001',
  VE_PREVIEW_002_WORKER_CRASHED: 'VE_PREVIEW_002',
  VE_PREVIEW_003_PORT_EXHAUSTED: 'VE_PREVIEW_003',
  // Protocol / IPC
  VE_PROTOCOL_001_VERSION_MISMATCH: 'VE_PROTOCOL_001',
  VE_PROTOCOL_002_INVALID_MESSAGE: 'VE_PROTOCOL_002',
  // Filesystem
  VE_FS_001_LOCK_HELD: 'VE_FS_001',
  // Internal
  VE_INTERNAL_999_ASSERT: 'VE_INTERNAL_999',
} as const;

export type ErrorCode = (typeof CODES)[keyof typeof CODES];
