import type { ApiEndpoint, MockSchema } from '@visual-edit/shared';

export interface BuildMSWHandlersInput {
  schemas: MockSchema[];
  endpoints: ApiEndpoint[];
  overrides: Record<string, unknown>;
}

export function buildMSWHandlers(input: BuildMSWHandlersInput): string {
  const { schemas, endpoints, overrides } = input;
  const schemaNames = new Set(schemas.map((s) => s.name));

  // Collect schemas referenced by endpoints (only those present in schema list get imports).
  const usedSchemas = new Set<string>();
  for (const ep of endpoints) usedSchemas.add(ep.schemaName);

  const lines: string[] = [];
  lines.push('// Auto-generated by @visual-edit/mock-runtime — do not edit.');
  lines.push("import { http, HttpResponse } from 'msw';");

  const importedMakers = [...usedSchemas].filter((s) => schemaNames.has(s)).map((s) => `make${s}`);
  if (importedMakers.length > 0) {
    lines.push(`import { ${importedMakers.join(', ')} } from './faker-bindings.js';`);
  }

  lines.push('');
  lines.push('export const handlers = [');

  for (const ep of endpoints) {
    const verb = ep.method.toLowerCase();
    const overrideKey = `${ep.method} ${ep.url}`;
    const override = overrides[overrideKey];

    let bodyExpr: string;
    if (override !== undefined) {
      bodyExpr = JSON.stringify(override, null, 2);
    } else if (schemaNames.has(ep.schemaName)) {
      bodyExpr = `make${ep.schemaName}()`;
    } else {
      bodyExpr = '{}';
    }

    const responseArgs =
      ep.status !== undefined ? `${bodyExpr}, { status: ${ep.status} }` : bodyExpr;

    lines.push(`  http.${verb}('${ep.url}', () => HttpResponse.json(${responseArgs})),`);
  }

  lines.push('];');
  return lines.join('\n');
}
