import type { MockSchema } from '@visual-edit/shared';

const STRING_FIELD_TABLE: Record<string, string> = {
  id: 'faker.string.uuid()',
  uuid: 'faker.string.uuid()',
  email: 'faker.internet.email()',
  firstName: 'faker.person.firstName()',
  lastName: 'faker.person.lastName()',
  fullName: 'faker.person.fullName()',
  name: 'faker.person.fullName()',
  username: 'faker.internet.userName()',
  password: `'***redacted***'`,
  url: 'faker.internet.url()',
  phone: 'faker.phone.number()',
  address: 'faker.location.streetAddress()',
  city: 'faker.location.city()',
  country: 'faker.location.country()',
  zipCode: 'faker.location.zipCode()',
  avatar: 'faker.image.avatar()',
  bio: 'faker.lorem.paragraph()',
  description: 'faker.lorem.sentences(2)',
  title: 'faker.lorem.sentence(4)',
  content: 'faker.lorem.paragraph()',
  createdAt: 'faker.date.recent().toISOString()',
  updatedAt: 'faker.date.recent().toISOString()',
  date: 'faker.date.recent().toISOString()',
  imageUrl: 'faker.image.url()',
  avatarUrl: 'faker.image.avatar()',
  image: 'faker.image.url()',
};

export function fieldToFakerCall(name: string, type: string): string {
  if (type === 'integer') return `faker.number.int({ min: 18, max: 65 })`;
  if (type === 'number') return `faker.number.float({ min: 0, max: 1000, fractionDigits: 2 })`;
  if (type === 'boolean') return `faker.datatype.boolean()`;
  if (type === 'string') {
    return STRING_FIELD_TABLE[name] ?? `faker.lorem.word()`;
  }
  return `null /* unsupported type ${type} */`;
}

export function buildFakerBindings(schemas: MockSchema[]): string {
  const lines: string[] = [];
  lines.push(`// Auto-generated by @visual-edit/mock-runtime — do not edit.`);
  lines.push(`import { faker } from '@faker-js/faker';`);
  lines.push('');

  for (const s of schemas) {
    const props = (s.shape.properties as Record<string, { type?: string }> | undefined) ?? {};
    lines.push(`export function make${s.name}() {`);
    lines.push(`  return {`);
    for (const [field, def] of Object.entries(props)) {
      const type = def.type ?? 'string';
      lines.push(`    ${field}: ${fieldToFakerCall(field, type)},`);
    }
    lines.push(`  };`);
    lines.push(`}`);
    lines.push('');
  }
  return lines.join('\n');
}
